### ISSUE TITLE
com.github.mangstadt class not found. Could it've been an error I made while building?

### ISSUE THREAD

**Issue by IsDisDaPizza** [mangstadt/ez-vcard#101]
In a nutshell: After painstakingly attempting to build the library (I'm a beginner programmer) for a week, it finally built without errors but when I try to use it, I get a ClassNotFoundException for com.github.mangstadt.vinnie.io.VObjectDataListener. What did I do wrong?

**Comment by mangstadt** [comment]
The class in question is part of a dependency of ez-vcard. You're probably not including the dependency's JAR file in the classpath when you run your program.

You're not using Maven to build the library?

**Comment by IsDisDaPizza** [comment]
I did use maven. Maven made 3 JAR files (Here's [a picture of the JAR files maven generated](https://user-images.githubusercontent.com/34038987/74209094-ea934680-4c4b-11ea-8719-569d0a1f54b9.png), all of which i added to the path). I also made sure the link was added in the dependencies inside the pom.xml file.

**Comment by mangstadt** [comment]
Maven stores the dependencies it downloads in a folder called ".m2", located at the root of your home directory. You'll find the JAR for the vinnie dependency in there.

If you need more help, you might want to check out the Apache Maven homepage and have a look at their documentation.

**Comment by IsDisDaPizza** [comment]
Boy am I glad my computer is stuck showing hidden folders. Thanks!
