### ISSUE TITLE
unable to get Photo when using URL

### ISSUE THREAD

**Issue by rajp6265** [mangstadt/ez-vcard#109]
Hello, 

I am not able to see photos when using the URL of an image. attaching generated vcf data along with it.
can anyone help regarding this?

BEGIN:VCARD
VERSION:3.0
PRODID:ez-vcard 0.11.0
N:;Ars
FN:Ars  
TITLE:
ORG:
ADR;TYPE=home:;;;;;9
LABEL;TYPE=home:\, \, 
TEL;TYPE=work:9
URL:
PHOTO;TYPE=jpeg;VALUE=https://png.pngtree.com/png-clipart/20190516/original/pngtree-infinity-initial-letter-dd-letter-d-logo-design-linked-png-image_3749553.jpg
END:VCARD

**Comment by mangstadt** [comment]
The PHOTO property is incorrectly formatted. It should be:

```
PHOTO;TYPE=jpeg;VALUE=uri:https://png.pngtree.com/png-clipart/20190516/original/pngtree-infinity-initial-letter-dd-letter-d-logo-design-linked-png-image_3749553.jpg
```

**Comment by rajp6265** [comment]
Hi, I have generated below vcf data from the library itself, still not getting the contact image.

**Java Code For adding Photo**: 
Photo photo = new Photo(payload.getProfilePhoto(), ImageType.JPEG);
vcard.addPhoto(photo);

BEGIN:VCARD
VERSION:3.0
PRODID:ez-vcard 0.11.0
N:;Ars
PHOTO;TYPE=jpeg;VALUE=uri:https://png.pngtree.com/png-clipart/20190516/orig
 inal/pngtree-infinity-initial-letter-dd-letter-d-logo-design-linked-png-im
 age_3749553.jpg
END:VCARD

I have tried after removing white space which is at the starting of a new line of image URL, but it does not work.

**Comment by mangstadt** [comment]
> I have tried after removing white space which is at the starting of a new line of image URL, but it does not work.

Do not remove that whitespace. It indicates that the line is folded.

**Comment by rajp6265** [comment]
Hi, 
With library-generated VCF data, the image could not be seen after importing vcf file.
is that anything wrong with the generated data?

**Comment by mangstadt** [comment]
Does the photo URL return an image file or does it open a web page? If it opens a web page, then that is probably why you are having trouble.

Assuming the URL is correct, I don't see anything wrong with the vCard you emailed me! :(

Maybe there is something wrong with the program that you are importing the VCF file into?

**Comment by rajp6265** [comment]
Yeah, I am digging into it and will let you know if I find any resolution.
Thank you for your time :)

**Comment by Maxim-Mazurok** [comment]
The images might be too big.
I'm using 320x320 base64-encoded JPEG, which is 10.74 KB in size

**Comment by skypesky** [comment]
> > I have tried after removing white space which is at the starting of a new line of image URL, but it does not work.
> 
> Do not remove that whitespace. It indicates that the line is folded.

related: https://www.rfc-editor.org/rfc/rfc6350.html#section-3.2
