### ISSUE TITLE
quoted-printable encoded entities are not correctly converted

### ISSUE THREAD

**Issue by j-ed** [mangstadt/ez-vcard#112]
The vCard 2.1 format allows to use quoted-printable encoded entities, which aren't allowed to be used in vCard 3.0/4.0 anymore.

If the library is used to convert a contact record from the vCard2.1 to the vCard 3.0 format the quoted-printable entities are currently kept and not decoded/converted correctly. This causes problems when international characters are used in, e.g. names, and usually prevents an app from importing data correctly. CC: @AndyScherzinger @tobiasKaminsky

The problem has been reported and described here:

https://github.com/nextcloud/contacts/issues/584#issuecomment-407656355
https://github.com/nextcloud/server/issues/10653

**Comment by mangstadt** [comment]
Thanks for the report. Fixed in fa82fc8.

Fix will be included in the next release.

See unit test: https://github.com/mangstadt/ez-vcard/blob/master/src/test/java/ezvcard/issue/Issue112.java
