### ISSUE TITLE
IMPP: case-insensitive comparison of schemes

### ISSUE THREAD

**Issue by rfc2822** [mangstadt/ez-vcard#123]
I suggest to perform case-insensitive comparision of schemes in `Impp.isProtocol`, so that not only `IMPP:icq:123456` would be recognized by `isProtocol("icq")` and `isIcq()` but also `IMPP:ICQ:123456`.

**Comment by mangstadt** [comment]
Thanks for catching that. Don't know what I was thinking. *facepalm*
