### ISSUE TITLE
Parsing from chunk of text

### ISSUE THREAD

**Issue by prrvchr** [mangstadt/ez-vcard#132]
Hi,

I am using ez-vcard `reader` to parse vcards from a database and this card by card.
Before parsing I must register a `VCardPropertyScribe` on the `reader` with `registerScribe` .

I did not find a method allowing me to use the same `reader` to process several cards in a row... (or several chunk of text)
Maybe I searched wrong...

Anyway thanks for this API.

**Comment by mangstadt** [comment]
If the vCards are all part of the same input stream, then they can be processed by the same `VCardReader`. Otherwise, you'll need to create a new `VCardReader` for each input stream.

**Comment by prrvchr** [comment]
Indeed, in fact I was looking for a `reader.next(chunk)` method.
Thank you, I'm closing...
