### ISSUE TITLE
[Compatibility] Treat KIND values case-insensitive

### ISSUE THREAD

**Issue by rfc2822** [mangstadt/ez-vcard#140]
There are clients/servers which set `KIND:GROUP` instead of `KIND:group` although RFC 6350 specifies "group" (lower-case) and values are case-sensitive.

For better compatibility, I suggest to make the `equals()` calls in `Kind.is…` case-insensitive:

https://github.com/mangstadt/ez-vcard/blob/b8f0a18cad11ed6172e1c7e18b6d78f07fe4fabf/src/main/java/ezvcard/property/Kind.java#L114-L116

**Comment by mangstadt** [comment]
Fixed in https://github.com/mangstadt/ez-vcard/commit/acbeb6613e155918a90673977b4e94a360252fb1.

**Comment by mangstadt** [comment]
ez-vcard version 0.12.1 has been released, which includes this bug fix!
