### ISSUE TITLE
GENDER: sex and gender mixed

### ISSUE THREAD

**Issue by rfc2822** [mangstadt/ez-vcard#27]
According to the VCard 4 specs, the GENDER value is used to identify sex and gender identity.

      The components correspond, in sequence, to the sex
      (biological), and gender identity.  Each component is optional.

      Sex component:  A single letter.  M stands for "male", F stands
         for "female", O stands for "other", N stands for "none or not
         applicable", U stands for "unknown".

      Gender identity component:  Free-form text.

                   GENDER-param = "VALUE=text" / any-param
                   GENDER-value = sex [";" text]

                   sex = "" / "M" / "F" / "O" / "N" / "U"

This makes sense, as M/F/O/N/U are values for sex. The gender identity is the free-form text.

However, in the API, `getGender()`/`setGender()` reads/writes the sex value and not the gender value, whereas `getText()`/`setText()` reads/writes the gender identity.

I suggest to rename `getGender()`/`setGender()` to `setSex()`/`getSex()` to make clear that the value is the biological sex. `getText()`/`setText()` is not for "extra explanatation", but the gender identity, which may even be given without a sex component. So maybe it should be renamed, too:

`getGender()`/`setGender()` → `getSex()`/`setSex()`
`getText()`/`setText()` → `getGenderIdentity()`/`setGenderIdentity()`

Gender and sex are also mixed in the documentation, for instance:

`isMale()
Determines if the gender is "male" or not.`

Should be:

`isMale()
Determines if the sex is "male" or not.`

**Comment by rfc2822** [comment]
Ok, I guess the whole property doesn't make much sense. Why should somebody want to store the biological sex of a contact? The existence of specific genitals are not really something I'd like to store for a contact, and the specs don't speak of gender.

**Comment by evert** [comment]
Just came across this: The vCard abstract data model might also used in a medical application. Might not be interesting for this project, but just something to keep in mind.
