### ISSUE TITLE
Android cannot write hCards due to freemarker dependency

### ISSUE THREAD

**Issue by ashutoshgngwr** [mangstadt/ez-vcard#28]
FreeMarker library is not supported on Android platform due to absence of `java.beans` package in Android Core Libraries and hence ez-vcard throws an exception when I try to create a HCard on Android.

How to fix this?

More details on the FreeMarker Android issue are available in [this StackOverflow.com thread](http://stackoverflow.com/questions/25929542/use-freemarker-library-in-android). In this thread, there is also a link to some patch that was supposed to make FreeMarker work on Android but it didn't work out either. :(

**Comment by mangstadt** [comment]
Thanks for reporting this.  I'll add a note to the Wiki about this.  I was been thinking about removing freemarker altogether, since it is only used to generate the hCard template.  This would be a good reason to do so. :/

**Comment by ashutoshgngwr** [comment]
When can I expect new release to be available? :p

**Comment by mangstadt** [comment]
Not sure, might be a while. :(
