### ISSUE TITLE
Strange Formatted Name when Writing to Stream

### ISSUE THREAD

**Issue by filipe-maia** [mangstadt/ez-vcard#44]
Hi,

Let's take a look to the following example:
````
	public static void main(String[] args) throws IOException {
		VCard vCard = new VCard();
		vCard.setVersion(VCardVersion.V2_1);
		vCard.addFormattedName(new FormattedName(
				"thisIsAName aVeryLongName thisIsAName aVeryLongName thisIsAName aVeryLongName, thisIsAName aVeryLongName thisIsAName aVeryLongName"));
		vCard.addTelephoneNumber("0123456789", TelephoneType.CELL);
		vCard.write(System.out);
	}
````
The output will be:
````
BEGIN:VCARD
VERSION:2.1
FN:thisIsAName aVeryLongName thisIsAName aVeryLongName thisIsAName aVeryLon
 gName\, thisIsAName aVeryLongName thisIsAName aVeryLongName
TEL;CELL:0123456789
X-PRODID:ez-vcard 0.9.8
END:VCARD
````

I know that's a strange name, but is it normal that the comma is preceded by a backslash? And why is the FN split into several lines (breaking words in two) starting each line with a space?

Thanks in advance.

**Comment by mangstadt** [comment]
Hi filipe,

> is it normal that the comma is preceded by a backslash?

Comma characters are special characters and must be escaped according to the vCard specification.

> And why is the FN split into several lines (breaking words in two) starting each line with a space?

That's called **folding**.  Lines that are longer than 75 characters are split into multiple lines.

**Comment by filipe-maia** [comment]
Thanks for the quick responce.

I've been doing a very simple converter beteween vsf to csv and vice-versa so I could easily edit my phone contacts in the PC in a cell sheet (your lib saved me a lot of time).

My phone has Android 5 and I'm using the stock Google contact manager. After importing the generated contacts to my phone, I've noticed that folding is not a problem, but the backslash characters show up in my contacts name. I found that strange and that was why I oppened this issue, but now I guess that's a Google contact manager problem.

**Comment by mangstadt** [comment]
It's also possible that you are "double-escaping" a property value somehow.  This would cause the backslash to appear in Google Contacts.

    FN:thisIsAName\\\, aVeryLongName

I don't know why Google Contacts wouldn't unescape commas in `FN` properties.  Even the example for the `FN` property in the specifications has an escaped comma in it!
