### ISSUE TITLE
ProductId value

### ISSUE THREAD

**Issue by Perrine1988** [mangstadt/ez-vcard#45]
Hi, 
I'm not able to update productId value. 

What steps will reproduce the problem?
1. vcard.setProductId("test");
2. System.out.println(Ezvcard.write(vcard).go());

What is the expected output?
PRODID:test

What is the actual output?
PRODID:ez-vcard 0.9.9

What version of ez-vcard are you using?
0.9.9

What version of Java are you using?
6

Please provide any additional information below.
If I get only productId, I get back the right value : 
System.out.println("product id : "+vcard.getProductId().getValue());
=> product id : test

**Comment by mangstadt** [comment]
Perrine,

When you write the vCard, you must set the "prodId" flag to "false", like so:

```java
VCard vcard = new VCard();
vcard.setProductId("test");
System.out.println(Ezvcard.write(vcard).prodId(false).go());
```

Please let me know if this helps.

**Comment by Perrine1988** [comment]
Michael, 
Thanks a lot for your fast answer (as each time), it works fine !
I'm sorry to disturb you for nothing... 
Thanks!

**Comment by mangstadt** [comment]
No problem, Perrine!
