### ISSUE TITLE
Custom Type for Telephone

### ISSUE THREAD

**Issue by leader80** [mangstadt/ez-vcard#50]
Hi all,
I would like to add a custom type to a telephone number:

```
final Telephone telCAP = new Telephone("123456789");
telCAP.getParameters().setCharset("ISO-8859-1");
telCAP.getParameters().addType("SPÉCciälö"));//
vcard.addTelephoneNumber(telCAP);
```
but the accents are not encoded, can someone please help me?

Regards
G.

**Comment by mangstadt** [comment]
Hi G,

Unfortunately, there is no way to specify the character set of a parameter value.  The CHARSET parameter only applies to property values.

If you want to use characters like the ones in your example inside parameter values, then you'll have to set the encoding of the entire vCard to UTF-8 or something of the sort.  For example:

```java
OutputStream out = new BufferedOutputStream(new FileOutputStream(new File("output.vcf")));
Writer writer = new OutputStreamWriter(out, "UTF-8");
VCardWriter vcardWriter = new VCardWriter(writer, VCardVersion.V3_0);
```
