### ISSUE TITLE
Support for RFC 6868

### ISSUE THREAD

**Issue by rfc2822** [mangstadt/ez-vcard#54]
Double-quotes can't be encoded with plain VCard 3/4. This is why [RFC 6868](https://tools.ietf.org/html/rfc6868) specifies a way to encode `"` (and `\n`) using the newly introduced `^` escape character.

It might be worth a thought whether RFC 6868 could be implemented in ez-vcard (and maybe enabled by default, and/or enabled/disabled by a configuration option). At the moment, I don't know any platforms implementing RFC 6868, but users are (understandably) [confused by the fact that they can't create contacts with `"` in fields like the address LABEL](https://forums.bitfire.at/topic/1078/error-while-uploading-created-modified-entries/), and RFC 6868 seems the only practicable solution for this problem.

Thanks for your great work.

**Comment by mangstadt** [comment]
Hey rfc,

ez-vcard already supports this.  It's turned **off** by default for write operations and turned **on** by default for read operations.  Use the [`VCardWriter.setCaretEncodingEnabled`](http://mangstadt.github.io/ez-vcard/javadocs/latest/ezvcard/io/text/VCardWriter.html#setCaretEncodingEnabled(boolean)) method to turn it on.

```java
VCard vcard = ...
VCardWriter writer = ...
writer.setCaretEncodingEnabled(true);
writer.write(vcard);
```

**Comment by rfc2822** [comment]
Ah, cool. Didn't see it in the API. Thanks

**Comment by mangstadt** [comment]
No problem.  Thank you for writing.
