### ISSUE TITLE
Address and telephone components separated by ";" instead of "," in version 3.0 and 4.0 

### ISSUE THREAD

**Issue by fernandagallina** [mangstadt/ez-vcard#60]
I am doing a unit test to check if my address field are filled I am using the following vCard: 

```text
BEGIN:vCard
VERSION:3.0
FN:Frank Dawson
ORG:Lotus Development Corporation
ADR;TYPE=WORK,POSTAL,PARCEL:;;6544 Battleford Drive
 ;Raleigh;NC;27613-3502;U.S.A.
TEL;TYPE=VOICE,MSG,WORK:+1-919-676-9515
TEL;TYPE=FAX,WORK:+1-919-676-9564
EMAIL;TYPE=INTERNET,PREF:Frank_Dawson@Lotus.com
EMAIL;TYPE=INTERNET:fdawson@earthlink.net
URL:http://home.earthlink.net/~fdawson
END:vCard
```

Unfortunately, checking my type parameters, I receive "WORK\" instead of "WORK". Changing  "TYPE=WORK,POSTAL" to "TYPE=WORK;POSTAL" I got the right parameter. 

my ref: https://en.wikipedia.org/wiki/VCard#vCard_2.1 / https://tools.ietf.org/html/rfc6350 / http://www.evenx.com/vcard-3-0-format-specification

**Comment by mangstadt** [comment]
Hi Fernanda,

I'm not quite sure what you're asking.  The components in an ADR property value are separated by semi-colon characters.  The values in a multi-valued parameter are separated by comma characters.  The vCard you posted is correctly formatted.

**Comment by fernandagallina** [comment]
Hello,

What am doing: I parse the vCard. Then I get the address and check the addresstype for that vCard. I try to check if is a AddressType.WORK.equals() but it returns false.

Debugging the code I see It is returning a "work\" string value instead of "work".

Is this the correct behavior?

**Comment by mangstadt** [comment]
I don't know why the TYPE parameter value would be "work\".  Can you post your code?

**Comment by fernandagallina** [comment]
I reviewed all code, it was an error we had in it, thank you for your help and time.

**Comment by mangstadt** [comment]
No problem, please let me know if you have any more questions.
