### ISSUE TITLE
BUILD ERROR AFTER ADDING LIBRARY

### ISSUE THREAD

**Issue by arashifunsho** [mangstadt/ez-vcard#65]
So, I added the latest version of the library via maven
`compile 'com.googlecode.ez-vcard:ez-vcard:0.9.11'`
and when i try to run the application I get 968 errors (obviously repeating, I believe its a single error) below is a snippet of the error

`Error:indicate that it is *not* an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(freemarker.template.utility.XmlEscape$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Information:BUILD SUCCESSFUL
Information:Total time: 1 mins 24.333 secs
Information:968 errors
`

This is what currently what my dependencies are:
`dependencies {
    compile 'com.tarun0.zxing-standalone:zxing-standalone:1.0.0'
    compile 'com.googlecode.ez-vcard:ez-vcard:0.9.11'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:support-v4:23.4.0'
    compile 'com.github.google:gson:1.7'
    compile files('libs/asmack-android-18-0.8.10.jar')
}`

Please help is needed urgently. Thanks

**Comment by mangstadt** [comment]
It looks like your build environment does not like Freemarker for some reason.  Freemarker is one of ez-vcard's dependencies.  However, you can safely exclude this dependency from your build as long as you are not using ez-vcard's hCard functionality.

I'm not too familiar with gradle, but I think this might work:

```
dependencies {
   compile ('com.googlecode.ez-vcard:ez-vcard:0.9.11') {
      exclude group: 'org.freemarker'
   }
}
```

Let me know if this helps.

**Comment by mangstadt** [comment]
Great!  Let me know if you have any more questions!

**Comment by arashifunsho** [comment]
Hmmm, do you have a snippet to allow me use Action.VIEW of android to initiate a Vcard display/save to contact? the one I adopted keep throwing an exception. thanks in advance

**Comment by mangstadt** [comment]
No, sorry. :-P
