### ISSUE TITLE
 java.lang.NoClassDefFoundError: freemarker.core.Interpolation

### ISSUE THREAD

**Issue by aitbaali** [mangstadt/ez-vcard#70]
```
AndroidStudio v: 2.2.2
Android v: 6.0.0 - API 23
compile 'com.googlecode.ez-vcard:ez-vcard:0.10.0'
```
I've tried to add
`compile group: 'org.freemarker', name: 'freemarker', version: '2.3.14'`
but not works

`FATAL EXCEPTION: main
        Process: app.myapp.com, PID: 3349
        java.lang.NoClassDefFoundError: freemarker.core.Interpolation at java.lang.Class.classForName(Native Method) at java.lang.Class.forName(Class.java:324) at com.activeandroid.ModelInfo.scanForModelClasses(ModelInfo.java:187) at com.activeandroid.ModelInfo.scanForModel(ModelInfo.java:152) at com.activeandroid.ModelInfo.<init>(ModelInfo.java:63) at com.activeandroid.Cache.initialize(Cache.java:66) at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:44) at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:34) at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:30) at com.activeandroid.app.Application.onCreate(Application.java:25) at app.myapp.com.MApplication.onCreate(MApplication.java:27) at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707) at android.app.ActivityThread.-wrap1(ActivityThread.java) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:148) at android.app.ActivityThread.main(ActivityThread.java:5417) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by mangstadt** [comment]
There might be something wrong with your build environment.  The `freemarker.core.Interpolation` class does not exist in the latest version of freemarker.
