### ISSUE TITLE
Where is VObjectDataListener defined?

### ISSUE THREAD

**Issue by andydude** [mangstadt/ez-vcard#79]
I tried using ez-vcard from Jython 
`from ezvcard.io.text import VCardReader`
and I got this:
`java.lang.NoClassDefFoundError: java.lang.NoClassDefFoundError: com/github/mangstadt/vinnie/io/VObjectDataListener`

**Comment by mangstadt** [comment]
Heya andydude,

The `VObjectDataListener` class is located in one of ez-vcard's dependencies.  The dependency is called "vinnie" and its project page is located here:

https://github.com/mangstadt/vinnie
