### ISSUE TITLE
all() method doesn't consider registered scribes

### ISSUE THREAD

**Issue by NeverWise** [mangstadt/ez-vcard#81]
In ChainingParser class the first() method works as expected but the all() method doesn't works.
I think the problem is that the all() method lacks of an if that is present in the first() method.
To be clear this if:
```java
if (index != null) {
	reader.setScribeIndex(index);
}
```

**Comment by mangstadt** [comment]
Thanks for catching that.  Fixed in 254fcec700f1db78a08ba996c066fe1b599f7680.
