### ISSUE TITLE
Problem with freemarker dependency.

### ISSUE THREAD

**Issue by isabsent** [mangstadt/ez-vcard#87]
I am using your lib as:

    compile 'com.googlecode.ez-vcard:ez-vcard:0.10.4'
and have a warning in Android Studio 3.1.3:

![eazy_vcard](https://user-images.githubusercontent.com/4918293/42436134-2c8cf934-8383-11e8-993e-4f6dea477804.png)

My configuration in root project gradle is:

    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
    }

    ext {
        minSdkVersion = 14
        targetSdkVersion = 25
        compileSdkVersion = 25
        buildToolsVersion = '25.0.3'
    
        androidSupportVersion = '25.3.1'
    }

**Comment by mangstadt** [comment]
Please do not post screenshots of error messages.

There must be something strange about the way the freemarker developers compiled the JAR that they uploaded to Maven Central.  You can safely exclude this dependency as long as you are not using ez-vcard to create hCards (a special format that allows you to embed vCards in HTML).

**Comment by isabsent** [comment]
Thanks for explanation!

**Comment by ddekany** [comment]
FreeMarker as of 2.3.28 is compiled for Java 5 target platform for backward compatibility (but with the Java 8 compiler); not sure if they call it old. Older FreeMarker 2.3.x versions are complied for even older Java versions, back to Java 1.2. Not sure which version is used here. But, it's just a warning anyway...
