### ISSUE TITLE
Datetime to comply with RFC 6350?

### ISSUE THREAD

**Issue by benoliver999** [mangstadt/ez-vcard#89]
This has recently come up because the python-vobject guys just changed their date formatting to the ISO 8601:2004 standard as mentioned in `4.3.2 - Basic format`

This resembles this:

`19850412T101530Z`

I went to moan at them but then saw that in RFC 6350 section 4.3 it says "Only the basic format is supported" - so actually that change is correct.

I think the datetime (at least for REV) looks like this: `2018-07-17T13:09:54Z` for ez-vcard. I may be way off the mark... I used davdroid to test.

**Comment by benoliver999** [comment]
Thank you!

**Comment by mangstadt** [comment]
Sure, thanks for posting
