### ISSUE TITLE
Java 10 does not support compiling to Java 5

### ISSUE THREAD

**Issue by PaulXiCao** [mangstadt/ez-vcard#90]
While compiling with maven
```bash
$ mvn compile
```
I get the following error
```bash
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] error: Source option 5 is no longer supported. Use 6 or later.
[ERROR] error: Target option 1.5 is no longer supported. Use 1.6 or later.
```
I found a similar discussion here: https://github.com/spring-guides/gs-maven/issues/21
But I dont know how to fix it though..

**Comment by PaulXiCao** [comment]
I solved the problem by downgrading from jdk10 to jdk8...

**Comment by mangstadt** [comment]
Target Java version increased to 6.

4c4893ccd41aa02cd2d55a71dd4fe20ffa53132f
