### ISSUE TITLE
Issue in Android 7+

### ISSUE THREAD

**Issue by saba7afi** [mangstadt/ez-vcard#98]
I've this errors in Android 7+ : 

- java.lang.ExceptionInInitializerError: 
  at ezvcard.Ezvcard.parse (Ezvcard.java:155)

**Comment by mangstadt** [comment]
Can you ask one of your developers to provide a more detailed stack trace?

**Comment by saba7afi** [comment]
Issue solved, it was causing by proguard minify enabled.
I just added this two lines to 'proguard-rules.pro':
`-keep,includedescriptorclasses class ezvcard.** { *; }
-keepclassmembers class ezvcard.** { *; }`

Thank you
